name: reviewdog
on: ["pull_request"]

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-staticcheck@v1
      with:
        filter_mode: diff_context
        fail_on_error: true